"""Canonical permission codes used across RBAC."""

PERMISSIONS = [
    ("tours.view", "View tours", "tours"),
    ("tours.create", "Create tours", "tours"),
    ("tours.update", "Update tours", "tours"),
    ("tours.delete", "Delete tours", "tours"),
    ("destinations.view", "View destinations", "destinations"),
    ("destinations.create", "Create destinations", "destinations"),
    ("destinations.update", "Update destinations", "destinations"),
    ("destinations.delete", "Delete destinations", "destinations"),
    ("departures.view", "View departures", "departures"),
    ("departures.create", "Create departures", "departures"),
    ("departures.update", "Update departures", "departures"),
    ("departures.delete", "Delete departures", "departures"),
    ("bookings.view", "View bookings", "bookings"),
    ("bookings.create", "Create bookings", "bookings"),
    ("bookings.update", "Update bookings", "bookings"),
    ("bookings.cancel", "Cancel bookings", "bookings"),
    ("customers.view", "View customers", "customers"),
    ("customers.update", "Update customers", "customers"),
    ("invoices.view", "View invoices", "invoices"),
    ("invoices.create", "Create invoices", "invoices"),
    ("invoices.update", "Update invoices", "invoices"),
    ("invoices.send", "Send invoices", "invoices"),
    ("payments.view", "View payments", "payments"),
    ("payments.record", "Record payments", "payments"),
    ("payments.verify", "Verify payments", "payments"),
    ("payments.refund", "Refund payments", "payments"),
    ("reports.view", "View reports", "reports"),
    ("content.view", "View content", "content"),
    ("content.create", "Create content", "content"),
    ("content.update", "Update content", "content"),
    ("content.delete", "Delete content", "content"),
    ("admins.view", "View admins", "admins"),
    ("admins.create", "Create admins", "admins"),
    ("admins.update", "Update admins", "admins"),
    ("admins.delete", "Delete admins", "admins"),
    ("settings.view", "View settings", "settings"),
    ("settings.update", "Update settings", "settings"),
    ("audit_logs.view", "View audit logs", "audit_logs"),
]

ROLE_PERMISSION_MAP = {
    "super-admin": [p[0] for p in PERMISSIONS],
    "operations-manager": [
        "tours.view",
        "tours.create",
        "tours.update",
        "tours.delete",
        "destinations.view",
        "destinations.create",
        "destinations.update",
        "destinations.delete",
        "departures.view",
        "departures.create",
        "departures.update",
        "departures.delete",
        "bookings.view",
        "bookings.create",
        "bookings.update",
        "bookings.cancel",
        "customers.view",
        "customers.update",
        "invoices.view",
        "payments.view",
        "reports.view",
        "content.view",
    ],
    "booking-manager": [
        "tours.view",
        "destinations.view",
        "departures.view",
        "bookings.view",
        "bookings.create",
        "bookings.update",
        "bookings.cancel",
        "customers.view",
        "customers.update",
        "invoices.view",
        "invoices.create",
        "invoices.update",
        "invoices.send",
        "payments.view",
    ],
    "finance": [
        "bookings.view",
        "customers.view",
        "invoices.view",
        "invoices.create",
        "invoices.update",
        "invoices.send",
        "payments.view",
        "payments.record",
        "payments.verify",
        "payments.refund",
        "reports.view",
    ],
    "content-manager": [
        "tours.view",
        "tours.update",
        "destinations.view",
        "destinations.create",
        "destinations.update",
        "content.view",
        "content.create",
        "content.update",
        "content.delete",
    ],
}
